name: publish github pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dzeromsk/nbp:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build
        run: make build
      - name: Publish
        run: make publish
        env:
          GITHUB_TOKEN: ${{ github.token }}
